
// this file is autogenerated - any modification will be overwritten
// unused symbols will not be linked in the final binary
// generated on 2023-03-20 23:02:42
// by ['../../../../tools/cert.py', '-s', 'jigsaw.w3.org', '-n', 'jigsaw']

#pragma once

////////////////////////////////////////////////////////////
// certificate chain for jigsaw.w3.org:443

const char* jigsaw_host = "https://raw.githubusercontent.com/abrilalum/openarms/main/dades";
const uint16_t jigsaw_port = 443;

// CN: sni.cloudflaressl.com => name: sni_cloudflaressl_com
// not valid before: 2023-02-14 00:00:00
// not valid after:  2024-02-14 23:59:59
const char fingerprint_sni_cloudflaressl_com [] PROGMEM = "04:4B:E2:1F:61:84:20:EE:0F:B7:69:71:0D:8A:CB:07:95:74";
const char pubkey_sni_cloudflaressl_com [] PROGMEM = R"PUBKEY(
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE/NU/7vfdymScyhfx81ieO8XiwGqq
TU4tjeWzSosWSpmQwnGmRqiU2h2wyT9uYxRme6uQ0yLedf4nz9ks+4OxtA==
-----END PUBLIC KEY-----
)PUBKEY";

// http://cacerts.digicert.com/CloudflareIncECCCA-3.crt
// CN: Cloudflare Inc ECC CA-3 => name: Cloudflare_Inc_ECC_CA_3
// not valid before: 2020-01-27 12:48:08
// not valid after:  2024-12-31 23:59:59
const char cert_Cloudflare_Inc_ECC_CA_3 [] PROGMEM = R"CERT(
-----BEGIN CERTIFICATE-----
MIIE9DCCA9ygAwIBAgISBEviH2GEIO4Pt2lxDYrLB5V0MA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yMzEyMjExMTM4MTNaFw0yNDAzMjAxMTM4MTJaMB4xHDAaBgNVBAMT
E29wZW5hcm1zLnh1cHh1cC5uZXQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQDBBlq1ByK1W1CefeqeQX/dmRt2Rlh6iXgMYwrreGdbyC66v+gXHZPOjH/W
eykkPDm35DlMDzaFJPrJJ2GsBH8XMxOh1l4oV3C4mSmVOSeOqq9A3oxHJlLNWNLc
Qqnt/ibWlNuGH0feJ8UkCvA3ApPsm3JHSVwFsJ0yjhlx/P/NoivbDdTM9WIsl+ww
ni7vvMVSsgpgNPOvF/nCGmLsRSNVfPvYevqpgHEVD5Nrav4ctSPF2OzWp0oEiKqn
N+4moL+xA+w0FqJDhFw6BBoNT67GRuJvf4MocTvrl+ACY4MMkYF+5yAhsgQCs8wY
yFhSvfzT/GoPlBwFdiPNVVQRNyAVAgMBAAGjggIWMIICEjAOBgNVHQ8BAf8EBAMC
BaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAw
HQYDVR0OBBYEFODXatEokBOakM5d0e2XiOuIFDBgMB8GA1UdIwQYMBaAFBQusxe3
WFbLrlAJQOYfr52LFMLGMFUGCCsGAQUFBwEBBEkwRzAhBggrBgEFBQcwAYYVaHR0
cDovL3IzLm8ubGVuY3Iub3JnMCIGCCsGAQUFBzAChhZodHRwOi8vcjMuaS5sZW5j
ci5vcmcvMB4GA1UdEQQXMBWCE29wZW5hcm1zLnh1cHh1cC5uZXQwEwYDVR0gBAww
CjAIBgZngQwBAgEwggEFBgorBgEEAdZ5AgQCBIH2BIHzAPEAdgA7U3d1Pi25gE6L
MFsG/kA7Z9hPw/THvQANLXJv4frUFwAAAYyMYi/tAAAEAwBHMEUCIQDuguMzcggB
xQMQ9l0nf5s3FEfC5MzS7X4jFVDvzgkr8QIga7t0aP46ygu7f5En84zWvAqN/6p/
G4YXe8fMufcSX4kAdwB2/4g/Crb7lVHCYcz1h7o0tKTNuyncaEIKn+ZnTFo6dAAA
AYyMYjBGAAAEAwBIMEYCIQC6g59e6o3folerDyy4/VdOnsjYT2+VtyDfmkEUfsdO
oAIhAM1JzcFA6c0Hfnv0UPRioD2hqzILMpkPfeJebyWPdnnKMA0GCSqGSIb3DQEB
CwUAA4IBAQBekjJXAYWkDelh6gxmNVzJQyWuiXeLQ4iOcpYV5z0m5AAg/zHbuiZO
TvWfnJGMf+yA56tKZGZBur6nzIwE7+9SupgYWEGivVEYb1DDeMjsOAn55bsUvoxJ
XrhgZkWU6GMsww5AYeWxInohzcVWxGj9W8/fa8jree7y3T16/kFrvUCb3i3gCBTa
47De15wyKENn35maW5B7gKTqChPUSt+EleUhnbat9yT7nvHFZpcvpUuJWWGWtiP7
ARQoOIVJE9zLVrSe/DK0pm3Xd+vLOJt1BfyHC7paGSH0jwEEGkqqRhVjM3CeCSKD
Uf9cqr3ksF4uTk0Eb7W8TnsQxR6eY83Z
-----END CERTIFICATE-----
)CERT";

// end of certificate chain for jigsaw.w3.org:443
////////////////////////////////////////////////////////////

